import "./globals.css";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import LayoutComp from "@/components/Layout";
import { ConfigProvider } from "antd";
import theme from "@/theme/themeConfig";

const inter = Inter({
  subsets: ["latin"],
  display: 'swap',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: [ 'normal' ]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <StyledComponentsRegistry>
          <ConfigProvider theme={theme} >
          <LayoutComp>{children}</LayoutComp>
          </ConfigProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
